--- # webserver
server:
  port: 80
  context-path: /

--- # logging
logging:
  level:

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

#mybatis:
#  config-location: classpath:mybatis-config.xml

#--- # datasource
#spring:
#  datasource:
#    url: jdbc:mysql://<ip>:3306/<db name>?useSSL=false
#    username:
#    password:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    initial-size: 1
#    maximum-pool-size: 10
#    connection-timeout: 5000


